/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'micwan' at '1/9/18 11:13 PM' with Gradle 3.2.1
 *
 * @author micwan, @date 1/9/18 11:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
